### ISSUE TITLE
Multiple materials do not work (2.80)

### ISSUE THREAD

**Issue by gigazelle** [DarklightGames/io_export_ase#5]
Attempting to export a mesh with more than one material throws an error.

Steps to reproduce:

1. Create a new project, add a new monkey mesh
2. Go to UV > Smart UV project, and auto-unwrap it using default settings.
3. Go to materials tab, add a material slot, then a single material.
4. Export the mesh
5. Note that it works just fine
6. Add a second material slot, and a second material
7. Export the mesh
8. Note that it throws an error:

```
Traceback (most recent call last):
File, line 1030 in execute
  aseMaterials = str( cMaterials() )
File, line 140, in __init__
  self.dump = cSubMaterials( self.material_list )
File, line 202, in __init__
  \n\t\t} }'''.format( index, cMaterial( slot ) )
File, line 239, in __init__
  self.shine = aseFloat( slot.specular_hardness / 511 )
AttributeError: 'Material' object has no attribute 'specular_hardness'

location: <unknown location>:-1
```

Please let me know if you are unable to reproduce, or if additional information is needed. Thanks!

**Comment by cmbasnett** [comment]
Fixed in f84864b.
