### ISSUE TITLE
*MATERIAL_LIST is missing the expected closing brace in exported ase files.

### ISSUE THREAD

**Issue by eGax** [DarklightGames/io_export_ase#6]
ASE files exported from B3D 2.80 with this addon are missing the expected closing brace from `*MATERIAL_LIST` so it has the `*GEOMOBJECT` in the `*MATERIAL_LIST` section. Make the ase appear corrupt and not load into other applications.

**Comment by cmbasnett** [comment]
Fixed in f84864b.
